name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Build and Test
    runs-on: macos-12

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: XCode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Bundle
        run: bundle install

      - name: Install Swiftgen
        run: brew install swiftgen

      - name: Install Sonar-Scanner
        run: brew install sonar-scanner

      - name: Install Lizard
        run: pip install lizard
        
      - name: Build and test
        run: bundle exec fastlane test sonar_login:"$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_RZAGRAM }}
